spring.application.name=SignLinkuageCapstone

# MySQL Datasource

spring.datasource.url=jdbc:mysql://localhost:3306/signlinkuage?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=QvLo!PD3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081
# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
debug=true

# JWT Configuration
jwt.secret=SignLinkuageCapstoneSecretKeyForJWTEncryption2024SuperSecretKeyMustBeAtLeast256BitsLong
jwt.expiration=86400000
